### ISSUE TITLE
Missing CyclOSM views

### ISSUE THREAD

**Issue by vfaronov** [mhajder/openstreetmap-tile-server-cyclosm#1]
Hi! Thanks for making this.

After running `import` and then `run` according to the readme, I was getting:
```
renderd[141]: An error occurred while loading the map layer 'ajt': Postgis Plugin: ERROR:  relation "cyclosm_ways" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM cyclosm_ways WHERE "way" ...
                                           ^
```
and the tile server was responding with 404 (Not Found).

After I manually executed CyclOSM’s [`views.sql`](https://github.com/cyclosm/cyclosm-cartocss-style/blob/4350a4635cab7df5e46007052babe3390c2fa51b/views.sql) inside the container’s `gis` database (and granted `ALL` on these views to `renderer`), I got the tile server to work.

I think your `Dockerfile` / `run.sh` are missing `views.sql` somewhere.

**Comment by mhajder** [comment]
Hey, Thanks for reporting a bug. 
It turns out that CycloOSM recently changed something. :(

Also I have been trying to create a docker image from scratch to add import elevation data (because now the map is without elevation data).

**Comment by punyidea** [comment]
I can confirm that using version 2.0.0 is a workaround to this issue. That is, when running with docker, changing `mhajder/openstreetmap-tile-server-cyclosm` to `mhajder/openstreetmap-tile-server-cyclosm:v2.0.0` in all docker commands (even just the run command) works well. Perhaps the readme should be updated.
