### ISSUE TITLE
404 error on tiles

### ISSUE THREAD

**Issue by punyidea** [mhajder/openstreetmap-tile-server-cyclosm#2]
Hi! Thanks so much for working on the project. I'm actually planning on setting up a cyclosm server for myself so I can plan a looong bike route using QGIS, without mooching off of their servers.
 I followed the instructions as written but am getting a 404 error when I try to access the tiles, in my browser, and in QGIS I get timeout errors. I know that the server is running because I am able to change `tile` to `mod_tile` in the URL and there I get the error that the image is corrupted or somehow has errors. 
 
 I think the import process went well, since it exited with error code 0. In any case, is this an issue with a change in cyclosm, or maybe from my side (a faulty setup)? I'd appreciate your help finding the issue. 
Thanks!

**Comment by punyidea** [comment]
after running the container in non-detached mode, I think this is issue #1. I'll close this and look there.

**Comment by mhajder** [comment]
Hi,
This is probably a bug related to cyclosm requiring their views to be imported as described in #1. Unfortunately, I didn't have time to fix it and add that import to install script.

Try to use an older version of the docker image like 2.0.0.
https://hub.docker.com/r/mhajder/openstreetmap-tile-server-cyclosm/tags
